int64   request_flag
---
bool is_done
string[]  top_box
float64[] top_CenterX
float64[] top_CenterY
float64[] top_Angle
string[] bottom_box
float64[] bottom_CenterX
float64[] bottom_CenterY
float64[] bottom_Angle